[project]
name="signal-ICT-HeerMehta-92400133037"
version = "0.1.1"
description = "A Python package for ICT signal processing"
authors = [
  { name = "Heer Mehta" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = []
